name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
    
    - name: make
      run: make
      
    - name: move binaries
      run: |
        mkdir upload
        mv ./CASBACnetStackCompileTest ./upload/
    
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: binary
        path: upload
    
        
